from __future__ import annotations

from typing import Annotated, Any, Optional, Sequence, TypedDict

try:  # Optional dependency
    from langgraph.graph import MessagesState as _MessagesState  # type: ignore
except Exception:  # pragma: no cover
    class _MessagesState(TypedDict, total=False):
        messages: Sequence[Any]


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    risky_history: Annotated[
        str, "Risky Agent's Conversation history"
    ]  # Conversation history
    safe_history: Annotated[
        str, "Safe Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_risky_response: Annotated[
        str, "Latest response by the risky analyst"
    ]  # Last response
    current_safe_response: Annotated[
        str, "Latest response by the safe analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(_MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]
    time_horizon: Annotated[
        str,
        "User-selected target holding period for this run (e.g., '1-2 weeks', '1-2 months')",
    ]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    final_trade_decision_structured: Annotated[dict, "Canonical validated JSON decision payload"]
    final_trade_decision_validation_error: Annotated[str, "Validation error for canonical decision payload"]
    market_snapshot: Annotated[dict, "Canonical market price snapshot used for decision anchoring and validation"]
    decision_guard: Annotated[dict, "Decision validation/repair telemetry and guardrail outcomes"]

    # Tool-loop guardrails and telemetry
    force_no_tools_for: Annotated[str, "Analyst key that must synthesize without tools for this turn"]
    tool_round_counts: Annotated[dict, "Tool rounds per analyst (e.g., market/social/news/fundamentals)"]
    # Backward-compatible alias for tool_round_counts.
    tool_call_counts: Annotated[dict, "Alias of tool_round_counts for legacy readers"]
    tool_call_total: Annotated[int, "Total number of tool rounds across analysts"]
    tool_calls_issued_by_agent: Annotated[dict, "Number of individual tool calls emitted by each analyst"]
    tool_calls_issued_total: Annotated[int, "Total individual tool calls emitted by analysts"]

    # Exact run-level LLM telemetry.
    llm_metrics: Annotated[dict, "Exact LLM/API usage counters for this run"]

    # Portfolio awareness (injected at graph init from brokerage API)
    portfolio_context: Annotated[str, "Current portfolio state from brokerage (positions, cash, buying power)"]

    # Market-session context (computed at graph init; baseline ET windows only)
    market_session: Annotated[dict, "Current US market session metadata"]
    market_session_context: Annotated[str, "Human-readable market-session context injected into prompts"]
